### ISSUE TITLE
House Action - On Canary

### ISSUE THREAD

**Issue by sircurse** [slawkens/myaac-plugins-old#7]
Hi, 

Not sure if the plugin should be compatible with Canary as well, but I m trying to run it and I got some errors while trying to bid, would be nice if we could have this plugin compatible with Canary too, is there anything I can do to fix it?

`2022/04/14 08:27:30 [error] 602#602: *167 FastCGI sent in stderr: "PHP message: PHP Notice:  Trying to access array offset on value of type bool in /var/www/html/system/pages/houses.php on line 422" while reading response header from upstream, client: 172.18.0.241, server: my.domain.com, request: "GET /?subtopic=houses&action=bid&house=3136 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "my.domain.com", referrer: "https://my.domain.com/?subtopic=houses&show=3136"

2022/04/14 08:27:52 [error] 602#602: *170 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column `otserver_db`.`houses`.`guildid` at row 1 in /var/www/html/system/libs/pot/OTS_Base_DB.php:188
Stack trace:
#0 /var/www/html/system/libs/pot/OTS_Base_DB.php(188): PDO->exec()
#1 /var/www/html/system/libs/pot/OTS_House.php(126): OTS_Base_DB->update()
#2 /var/www/html/system/pages/houses.php(373): OTS_House->save()
#3 /var/www/html/index.php(488): require('/var/www/html/s...')
#4 {main}
  thrown in /var/www/html/system/libs/pot/OTS_Base_DB.php on line 188" while reading response header from upstream, client: 172.18.0.241, server: my.domain.com, request: "POST /?houses HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "my.domain.com", referrer: "https://my.domain.com/?subtopic=houses&action=bid&house=3136"`

**Comment by augustorajas** [comment]
This plugin is what I'm looking forward to most of all time!
